### ISSUE TITLE
`serde_json::Value`: cannot deserialize primitive at the top level.Try deserializing into a struct.

### ISSUE THREAD

**Issue by Altair-Bueno** [samscott89/serde_qs#77]
### Summary

Cannot deserialize query string into dynamic objects such as `serde_json::Value` or `toml::Value`

### Current behaviour

Deserialization fails. Serialization succeeds

### Expected behaviour

Serialization and deserialization shouldn't fail on dynamic objects.

### Minimal example

```rust
// main.rs
fn main() -> Result<(), serde_qs::Error> {
    let payload = "hello=10";
    let json_value: serde_json::Value = serde_qs::from_str(payload)?;
    let expected = serde_json::json!({ "hello": 10 });
    assert_eq!(json_value, expected);
    Ok(())
}
```

```toml
# Cargo.toml
[package]
name = "primitive-top-level"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.91"
serde_qs = "0.11.0"
```

```text
Error: Custom("cannot deserialize primitive at the top level.Try deserializing into a struct.")
```
